version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aqa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 270996Dcp1488
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  gate-simulator:
    build:
      context: ./gate-simulator
      dockerfile: Dockerfile
    container_name: aqa-gate-simulator
    ports:
      - "9999:9999"
    restart: unless-stopped

  aqa-shop:
    image: eclipse-temurin:17-jdk
    container_name: aqa-shop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_CREDIT_GATE_URL: http://gate-simulator:9999/credit
      SPRING_PAYMENT_GATE_URL: http://gate-simulator:9999/payment
    depends_on:
      - mysql
      - gate-simulator
    volumes:
      - ./aqa-shop.jar:/app/aqa-shop.jar
    command: ["java", "-jar", "/app/aqa-shop.jar"]
    restart: unless-stopped

volumes:
  mysql-data:

